#include "mcrinvitem.h"

#include "mcrinvslot.h"

#include <QDebug>
#include <QPainter>
#include <QGraphicsColorizeEffect>

MCRInvItem::MCRInvItem(QWidget *parent, QString id) : QLabel(parent)
{   
    setMinimumSize(32, 32);

    QString iconpath;
    QPixmap iconpix;

    if(id.startsWith(QStringLiteral("minecraft:")))
        id.remove(0, 10);

    if(id == "debug_stick") {
        iconpath = ":minecraft/texture/item/stick.png";
        iconpix = QPixmap(iconpath);
    } else if(id == "enchanted_golden_apple") {
        iconpath = ":minecraft/texture/item/golden_apple.png";
        iconpix = QPixmap(iconpath);
    } else if(id == "potion" || id == "lingering_potion"
                             || id == "splash_potion") {
        QPixmap overlay = QPixmap(":minecraft/texture/item/potion_overlay.png");
        {
            QPainter painter(&overlay);
            painter.setCompositionMode(QPainter::CompositionMode_SourceAtop);
            painter.setOpacity(0.5);
            painter.setBackgroundMode(Qt::OpaqueMode);
            painter.fillRect(overlay.rect(), QBrush(QColor("#CA00CA")));
            painter.end();
        }
        iconpix = QPixmap(":minecraft/texture/item/"+id+".png");
        {
            QPainter painter(&iconpix);
            painter.setCompositionMode(QPainter::CompositionMode_SourceOver);

            painter.drawPixmap(overlay.rect(), overlay);
            painter.end();
        }
    } else if(id == "leather_boots" || id == "leather_chestplate"
                                    || id == "leather_helmet"
                                    || id == "leather_leggings"
                                    || id == "leather_horse_armor") {
                iconpix = QPixmap(":minecraft/texture/item/"+id+".png");
        {
            QPainter painter(&iconpix);
//            painter.setCompositionMode(QPainter::CompositionMode_SourceAtop);
//            painter.setOpacity(0.83);
//            painter.setBackgroundMode(Qt::OpaqueMode);
//            painter.fillRect(iconpix.rect(), QBrush(QColor("#A06540")));
            painter.setCompositionMode(QPainter::CompositionMode_SourceOver);
            QPixmap overlay = QPixmap(":minecraft/texture/item/"+id+"_overlay.png");
            painter.drawPixmap(overlay.rect(), overlay);
            painter.end();
        }
    } else if(id == "firework_star") {
        QPixmap overlay = QPixmap(":minecraft/texture/item/firework_star_overlay.png");
        iconpix = QPixmap(":minecraft/texture/item/firework_star.png");
        {
            QPainter painter(&iconpix);
            painter.setCompositionMode(QPainter::CompositionMode_SourceOver);

            painter.drawPixmap(overlay.rect(), overlay);
            painter.end();
        }
    } else if(id == "tipped_arrow") {
        QPixmap overlay = QPixmap(":minecraft/texture/item/tipped_arrow_head.png");
        {
            QPainter painter(&overlay);
            painter.setCompositionMode(QPainter::CompositionMode_SourceAtop);
            painter.setOpacity(0.5);
            painter.setBackgroundMode(Qt::OpaqueMode);
            painter.fillRect(overlay.rect(), QBrush(QColor("#CA00CA")));
            painter.end();
        }
        iconpix = QPixmap(":minecraft/texture/item/tipped_arrow.png");
        {
            QPainter painter(&iconpix);
            painter.setCompositionMode(QPainter::CompositionMode_SourceOver);

            painter.drawPixmap(overlay.rect(), overlay);
            painter.end();
        }
    } else {
        iconpath = ":minecraft/texture/item/"+id+".png";
        iconpix = QPixmap(iconpath);
    }

    if(!iconpix) {
        iconpath = ":minecraft/texture/block/"+id+".png";
        iconpix = QPixmap(iconpath);
    }

    if(!iconpix) {
        if(id.endsWith("_spawn_egg")) {
            iconpix = QPixmap(":minecraft/texture/item/spawn_egg.png");
            {
                QPainter painter(&iconpix);
                painter.setCompositionMode(QPainter::CompositionMode_DestinationOver);
                QPixmap overlay = QPixmap(":minecraft/texture/item/spawn_egg_overlay.png");
                painter.drawPixmap(overlay.rect(), overlay);
                painter.end();
            }
        }
    }

//    if(id == "vine") {
//        {
//            QPainter painter(&iconpix);
//            //painter.setCompositionMode(QPainter::CompositionMode_DestinationIn);
//            painter.setCompositionMode(QPainter::CompositionMode_SourceAtop);
//            //QBrush brush = QBrush(QColor("#7748B518").darker(200));
//            QColor color = QColor("#7748B518");
//            //color.setHsv(color.hue(), color.saturation(), color.value()/2, color.alpha());
//            color.setHsv(color.hue(), qMin(color.saturation(), 1), color.value()*1, color.alpha());
//            qDebug() << color;
//            QBrush brush = QBrush(color);
//            painter.fillRect(iconpix.rect(), brush);
//            painter.end();
//        }
//    }

    if(!iconpix) {
        qDebug() << "unknown ID: " + id;
        iconpix = QPixmap(16, 16);
        iconpix.fill("#FF00DC");
        {
            QPainter painter(&iconpix);
            //painter.setCompositionMode(QPainter::CompositionMode_DestinationOver);
            //QBrush brush(QColor("#FF00DC"));
            //painter.fillRect(iconpix.rect(), brush);
            QBrush brush = QBrush(QColor("#000"));
            painter.fillRect(8, 0, 8, 8, brush);
            painter.fillRect(0, 8, 8, 8, brush);
            painter.end();
        }
    }
    iconpix = iconpix.scaled(32, 32, Qt::KeepAspectRatio);
    //qDebug() << iconpix;
    setPixmap(iconpix);
    setAlignment(Qt::AlignCenter);
    setAttribute(Qt::WA_DeleteOnClose);
    if(itemList().contains(id)) {
        setName(itemList().value(id));
        setToolTip(name);
    } else {
        setToolTip("Unknown item: "+id);
    }
    //invItem->show();

    this->namespacedID = id;

    show();

    setupItem();
}

void MCRInvItem::setupItem() {

}

QString MCRInvItem::getName() {
    return this->name;
}

void MCRInvItem::setName(const QString &name) {
    this-> name = name;
}

QMap<QString, QString> MCRInvItem::itemList() {
    QMap<QString, QString> itemlist = {
        {"acacia_button", "Acacia Button"},
        {"acacia_door", "Acacia Door"},
        {"acacia_fence_gate", "Acacia Fence Gate"},
        {"acacia_fence", "Acacia Fence"},
        {"acacia_leaves", "Acacia Leaves"},
        {"acacia_log", "Acacia Log"},
        {"acacia_planks", "Acacia Planks"},
        {"acacia_pressure_plate", "Acacia Pressure Plate"},
        {"acacia_sapling", "Acacia Sapling"},
        {"acacia_sign", "Acacia Sign"},
        {"acacia_slab", "Acacia Slab"},
        {"acacia_stairs", "Acacia Stairs"},
        {"acacia_trapdoor", "Acacia Trapdoor"},
        {"acacia_wood", "Acacia Wood"},
        {"activator_rail", "Activator Rail"},
        {"allium", "Allium"},
        {"andesite", "Andesite"},
        {"andesite_slab", "Andesite Slab"},
        {"andesite_stairs", "Andesite Stairs"},
        {"andesite_wall", "Andesite Wall"},
        {"anvil", "Anvil"},
        {"azure_bluet", "Azure Bluet"},
        {"bamboo", "Bamboo"},
        {"barrel", "Barrel"},
        {"barrier", "Barrier"},
        {"beacon", "Beacon"},
        {"bedrock", "Bedrock"},
        {"beehive", "Beehive"},
        {"bee_nest", "Bee Nest"},
        {"bell", "Bell"},
        {"birch_button", "Birch Button"},
        {"birch_door", "Birch Door"},
        {"birch_fence_gate", "Birch Fence Gate"},
        {"birch_fence", "Birch Fence"},
        {"birch_leaves", "Birch Leaves"},
        {"birch_log", "Birch Log"},
        {"birch_planks", "Birch Planks"},
        {"birch_pressure_plate", "Birch Pressure Plate"},
        {"birch_sapling", "Birch Sapling"},
        {"birch_sign", "Birch Sign"},
        {"birch_slab", "Birch Slab"},
        {"birch_stairs", "Birch Stairs"},
        {"birch_trapdoor", "Birch Trapdoor"},
        {"birch_wood", "Birch Wood"},
        {"black_banner", "Black Banner"},
        {"black_bed", "Black Bed"},
        {"black_carpet", "Black Carpet"},
        {"black_concrete_powder", "Black Concrete Powder"},
        {"black_concrete", "Black Concrete"},
        {"black_glazed_terracotta", "Black Glazed Terracotta"},
        {"black_shulker_box", "Black Shulker Box"},
        {"black_stained_glass", "Black Stained Glass"},
        {"black_stained_glass_pane", "Black Stained Glass Pane"},
        {"black_terracotta", "Black Terracotta"},
        {"black_wool", "Black Wool"},
        {"blast_furnace", "Blast Furnace"},
        {"blue_banner", "Blue Banner"},
        {"blue_bed", "Blue Bed"},
        {"blue_carpet", "Blue Carpet"},
        {"blue_concrete_powder", "Blue Concrete Powder"},
        {"blue_concrete", "Blue Concrete"},
        {"blue_glazed_terracotta", "Blue Glazed Terracotta"},
        {"blue_ice", "Blue Ice"},
        {"blue_orchid", "Blue Orchid"},
        {"blue_shulker_box", "Blue Shulker Box"},
        {"blue_stained_glass", "Blue Stained Glass"},
        {"blue_stained_glass_pane", "Blue Stained Glass Pane"},
        {"blue_terracotta", "Blue Terracotta"},
        {"blue_wool", "Blue Wool"},
        {"bone_block", "Bone Block"},
        {"bookshelf", "Bookshelf"},
        {"brain_coral", "Brain Coral"},
        {"brain_coral_block", "Brain Coral Block"},
        {"brain_coral_fan", "Brain Coral Fan"},
        {"brewing_stand", "Brewing Stand"},
        {"brick_slab", "Brick Slab"},
        {"brick_stairs", "Brick Stairs"},
        {"brick_wall", "Brick Wall"},
        {"bricks", "Bricks"},
        {"brown_banner", "Brown Banner"},
        {"brown_bed", "Brown Bed"},
        {"brown_carpet", "Brown Carpet"},
        {"brown_concrete_powder", "Brown Concrete Powder"},
        {"brown_concrete", "Brown Concrete"},
        {"brown_glazed_terracotta", "Brown Glazed Terracotta"},
        {"brown_mushroom_block", "Brown Mushroom Block"},
        {"brown_mushroom", "Brown Mushroom"},
        {"brown_shulker_box", "Brown Shulker Box"},
        {"brown_stained_glass", "Brown Stained Glass"},
        {"brown_stained_glass_pane", "Brown Stained Glass Pane"},
        {"brown_terracotta", "Brown Terracotta"},
        {"brown_wool", "Brown Wool"},
        {"bubble_column", "Bubble Column"},
        {"bubble_coral", "Bubble Coral"},
        {"bubble_coral_block", "Bubble Coral Block"},
        {"cactus", "Cactus"},
        {"cake", "Cake"},
        {"campfire", "Campfire"},
        {"cartography_table", "Cartography Table"},
        {"carved_pumpkin", "Carved Pumpkin"},
        {"cauldron", "Cauldron"},
        {"chain_command_block", "Chain Command Block"},
        {"chest", "Chest"},
        {"chipped_anvil", "Chipped Anvil"},
        {"chiseled_quartz_block", "Chiseled Quartz Block"},
        {"chiseled_red_sandstone", "Chiseled Red Sandstone"},
        {"chiseled_sandstone", "Chiseled Sandstone"},
        {"chiseled_stone_bricks", "Chiseled Stone Bricks"},
        {"chorus_flower", "Chorus Flower"},
        {"chorus_plant", "Chorus Plant"},
        {"clay", "Clay"},
        {"coal_block", "Block of Coal"},
        {"coal_ore", "Coal Ore"},
        {"coarse_dirt", "Coarse Dirt"},
        {"cobblestone", "Cobblestone"},
        {"cobblestone_slab", "Cobblestone Slab"},
        {"cobblestone_stairs", "Cobblestone Stairs"},
        {"cobblestone_wall", "Cobblestone Wall"},
        {"cobweb", "Cobweb"},
        {"command_block", "Command Block"},
        {"comparator", "Redstone Comparator"},
        {"composter", "Composter"},
        {"conduit", "Conduit"},
        {"cornflower", "Cornflower"},
        {"cracked_stone_bricks", "Cracked Stone Bricks"},
        {"crafting_table", "Crafting Table"},
        {"creeper_head", "Creeper Head"},
        {"cut_red_sandstone", "Cut Red Sandstone"},
        {"cut_red_sandstone_slab", "Cut Red Sandstone Slab"},
        {"cut_sandstone", "Cut Sandstone"},
        {"cut_sandstone_slab", "Cut Sandstone Slab"},
        {"cyan_banner", "Cyan Banner"},
        {"cyan_bed", "Cyan Bed"},
        {"cyan_carpet", "Cyan Carpet"},
        {"cyan_concrete_powder", "Cyan Concrete Powder"},
        {"cyan_concrete", "Cyan Concrete"},
        {"cyan_glazed_terracotta", "Cyan Glazed Terracotta"},
        {"cyan_shulker_box", "Cyan Shulker Box"},
        {"cyan_stained_glass", "Cyan Stained Glass"},
        {"cyan_stained_glass_pane", "Cyan Stained Glass Pane"},
        {"cyan_terracotta", "Cyan Terracotta"},
        {"cyan_wool", "Cyan Wool"},
        {"damaged_anvil", "Damaged Anvil"},
        {"dandelion", "Dandelion"},
        {"dark_oak_button", "Dark Oak Button"},
        {"dark_oak_door", "Dark Oak Door"},
        {"dark_oak_fence_gate", "Dark Oak Fence Gate"},
        {"dark_oak_fence", "Dark Oak Fence"},
        {"dark_oak_leaves", "Dark Oak Leaves"},
        {"dark_oak_log", "Dark Oak Log"},
        {"dark_oak_planks", "Dark Oak Planks"},
        {"dark_oak_pressure_plate", "Dark Oak Pressure Plate"},
        {"dark_oak_sapling", "Dark Oak Sapling"},
        {"dark_oak_sign", "Dark Oak Sign"},
        {"dark_oak_slab", "Dark Oak Slab"},
        {"dark_oak_stairs", "Dark Oak Stairs"},
        {"dark_oak_trapdoor", "Dark Oak Trapdoor"},
        {"dark_oak_wood", "Dark Oak Wood"},
        {"dark_prismarine", "Dark Prismarine"},
        {"dark_prismarine_slab", "Dark Prismarine Slab"},
        {"dark_prismarine_stairs", "Dark Prismarine Stairs"},
        {"daylight_detector", "Daylight Detector"},
        {"dead_brain_coral", "Dead Brain Coral"},
        {"dead_brain_coral_block", "Dead Brain Coral Block"},
        {"dead_bubble_coral", "Dead Bubble Coral"},
        {"dead_bubble_coral_block", "Dead Bubble Coral Block"},
        {"dead_bush", "Dead Bush"},
        {"dead_fire_coral", "Dead Fire Coral"},
        {"dead_fire_coral_block", "Dead Fire Coral Block"},
        {"dead_horn_coral", "Dead Horn Coral"},
        {"dead_horn_coral_block", "Dead Horn Coral Block"},
        {"dead_tube_coral", "Dead Tube Coral"},
        {"dead_tube_coral_block", "Dead Tube Coral Block"},
        {"detector_rail", "Detector Rail"},
        {"diamond_block", "Block of Diamond"},
        {"diamond_ore", "Diamond Ore"},
        {"diorite", "Diorite"},
        {"diorite_slab", "Diorite Slab"},
        {"diorite_stairs", "Diorite Stairs"},
        {"diorite_wall", "Diorite Wall"},
        {"dirt", "Dirt"},
        {"dispenser", "Dispenser"},
        {"dragon_egg", "Dragon Egg"},
        {"dragon_head", "Dragon Head"},
        {"dried_kelp_block", "Dried Kelp Block"},
        {"dropper", "Dropper"},
        {"emerald_block", "Block of Emerald"},
        {"emerald_ore", "Emerald Ore"},
        {"enchanting_table", "Enchanting Table"},
        {"end_portal_frame", "End Portal Frame"},
        {"end_rod", "End Rod"},
        {"end_stone", "End Stone"},
        {"end_stone_brick_slab", "End Stone Brick Slab"},
        {"end_stone_brick_stairs", "End Stone Brick Stairs"},
        {"end_stone_brick_wall", "End Stone Brick Wall"},
        {"end_stone_bricks", "End Stone Bricks"},
        {"ender_chest", "Ender Chest"},
        {"farmland", "Farmland"},
        {"fern", "Fern"},
        {"fire_coral", "Fire Coral"},
        {"fire_coral_block", "Fire Coral Block"},
        {"fletching_table", "Fletching Table"},
        {"flower_pot", "Flower Pot"},
        {"furnace", "Furnace"},
        {"glass", "Glass"},
        {"glass_pane", "Glass Pane"},
        {"glowstone", "Glowstone"},
        {"gold_block", "Block of Gold"},
        {"gold_ore", "Gold Ore"},
        {"granite", "Granite"},
        {"granite_slab", "Granite Slab"},
        {"granite_stairs", "Granite Stairs"},
        {"granite_wall", "Granite Wall"},
        {"grass_block", "Grass Block"},
        {"grass_path", "Grass Path"},
        {"grass", "Grass"},
        {"gravel", "Gravel"},
        {"gray_banner", "Gray Banner"},
        {"gray_bed", "Gray Bed"},
        {"gray_carpet", "Gray Carpet"},
        {"gray_concrete_powder", "Gray Concrete Powder"},
        {"gray_concrete", "Gray Concrete"},
        {"gray_glazed_terracotta", "Gray Glazed Terracotta"},
        {"gray_shulker_box", "Gray Shulker Box"},
        {"gray_stained_glass", "Gray Stained Glass"},
        {"gray_stained_glass_pane", "Gray Stained Glass Pane"},
        {"gray_terracotta", "Gray Terracotta"},
        {"gray_wool", "Gray Wool"},
        {"green_banner", "Green Banner"},
        {"green_bed", "Green Bed"},
        {"green_carpet", "Green Carpet"},
        {"green_concrete_powder", "Green Concrete Powder"},
        {"green_concrete", "Green Concrete"},
        {"green_glazed_terracotta", "Green Glazed Terracotta"},
        {"green_shulker_box", "Green Shulker Box"},
        {"green_stained_glass", "Green Stained Glass"},
        {"green_stained_glass_pane", "Green Stained Glass Pane"},
        {"green_terracotta", "Green Terracotta"},
        {"green_wool", "Green Wool"},
        {"grindstone", "Grindstone"},
        {"hay_block", "Hay Bale"},
        {"heavy_weighted_pressure_plate", "Heavy Weighted Pressure Plate"},
        {"honey_block", "Honey Block"},
        {"honeycomb_block", "Honeycomb Block"},
        {"hopper", "Hopper"},
        {"horn_coral", "Horn Coral"},
        {"horn_coral_block", "Horn Coral Block"},
        {"ice", "Ice"},
        {"infested_chiseled_stone_bricks", "Infested Chiseled Stone Bricks"},
        {"infested_cobblestone", "Infested Cobblestone"},
        {"infested_cracked_stone_bricks", "Infested Cracked Stone Bricks"},
        {"infested_mossy_stone_bricks", "Infested Mossy Stone Bricks"},
        {"infested_stone", "Infested Stone"},
        {"infested_stone_bricks", "Infested Stone Bricks"},
        {"iron_bars", "Iron Bars"},
        {"iron_door", "Iron Door"},
        {"iron_block", "Block of Iron"},
        {"iron_ore", "Iron Ore"},
        {"iron_trapdoor", "Iron Trapdoor"},
        {"jack_o_lantern", "Jack o'Lantern"},
        {"jigsaw", "Jigsaw Block"},
        {"jukebox", "Jukebox"},
        {"jungle_button", "Jungle Button"},
        {"jungle_door", "Jungle Door"},
        {"jungle_fence_gate", "Jungle Fence Gate"},
        {"jungle_fence", "Jungle Fence"},
        {"jungle_leaves", "Jungle Leaves"},
        {"jungle_log", "Jungle Log"},
        {"jungle_planks", "Jungle Planks"},
        {"jungle_pressure_plate", "Jungle Pressure Plate"},
        {"jungle_sapling", "Jungle Sapling"},
        {"jungle_sign", "Jungle Sign"},
        {"jungle_slab", "Jungle Slab"},
        {"jungle_stairs", "Jungle Stairs"},
        {"jungle_trapdoor", "Jungle Trapdoor"},
        {"jungle_wood", "Jungle Wood"},
        {"kelp", "Kelp"},
        {"ladder", "Ladder"},
        {"lantern", "Lantern"},
        {"lapis_block", "Lapis Lazuli Block"},
        {"lapis_ore", "Lapis Lazuli Ore"},
        {"large_fern", "Large Fern"},
        {"lectern", "Lectern"},
        {"lever", "Lever"},
        {"light_blue_banner", "Light Blue Banner"},
        {"light_blue_bed", "Light Blue Bed"},
        {"light_blue_carpet", "Light Blue Carpet"},
        {"light_blue_concrete_powder", "Light Blue Concrete Powder"},
        {"light_blue_concrete", "Light Blue Concrete"},
        {"light_blue_glazed_terracotta", "Light Blue Glazed Terracotta"},
        {"light_blue_shulker_box", "Light Blue Shulker Box"},
        {"light_blue_stained_glass", "Light Blue Stained Glass"},
        {"light_blue_stained_glass_pane", "Light Blue Stained Glass Pane"},
        {"light_blue_terracotta", "Light Blue Terracotta"},
        {"light_blue_wool", "Light Blue Wool"},
        {"light_gray_banner", "Light Gray Banner"},
        {"light_gray_bed", "Light Gray Bed"},
        {"light_gray_carpet", "Light Gray Carpet"},
        {"light_gray_concrete_powder", "Light Gray Concrete Powder"},
        {"light_gray_concrete", "Light Gray Concrete"},
        {"light_gray_glazed_terracotta", "Light Gray Glazed Terracotta"},
        {"light_gray_shulker_box", "Light Gray Shulker Box"},
        {"light_gray_stained_glass", "Light Gray Stained Glass"},
        {"light_gray_stained_glass_pane", "Light Gray Stained Glass Pane"},
        {"light_gray_terracotta", "Light Gray Terracotta"},
        {"light_gray_wool", "Light Gray Wool"},
        {"light_weighted_pressure_plate", "Light Weighted Pressure Plate"},
        {"lilac", "Lilac"},
        {"lily_pad", "Lily Pad"},
        {"lily_of_the_valley", "Lily of the Valley"},
        {"lime_banner", "Lime Banner"},
        {"lime_bed", "Lime Bed"},
        {"lime_carpet", "Lime Carpet"},
        {"lime_concrete_powder", "Lime Concrete Powder"},
        {"lime_concrete", "Lime Concrete"},
        {"lime_glazed_terracotta", "Lime Glazed Terracotta"},
        {"lime_shulker_box", "Lime Shulker Box"},
        {"lime_stained_glass", "Lime Stained Glass"},
        {"lime_stained_glass_pane", "Lime Stained Glass Pane"},
        {"lime_terracotta", "Lime Terracotta"},
        {"lime_wool", "Lime Wool"},
        {"loom", "Loom"},
        {"magenta_banner", "Magenta Banner"},
        {"magenta_bed", "Magenta Bed"},
        {"magenta_carpet", "Magenta Carpet"},
        {"magenta_concrete_powder", "Magenta Concrete Powder"},
        {"magenta_concrete", "Magenta Concrete"},
        {"magenta_glazed_terracotta", "Magenta Glazed Terracotta"},
        {"magenta_shulker_box", "Magenta Shulker Box"},
        {"magenta_stained_glass", "Magenta Stained Glass"},
        {"magenta_stained_glass_pane", "Magenta Stained Glass Pane"},
        {"magenta_terracotta", "Magenta Terracotta"},
        {"magenta_wool", "Magenta Wool"},
        {"magma_block", "Magma Block"},
        {"melon", "Melon"},
        {"mossy_cobblestone", "Mossy Cobblestone"},
        {"mossy_cobblestone_slab", "Mossy Cobblestone Slab"},
        {"mossy_cobblestone_stairs", "Mossy Cobblestone Stairs"},
        {"mossy_cobblestone_wall", "Mossy Cobblestone Wall"},
        {"mossy_stone_brick_slab", "Mossy Stone Brick Slab"},
        {"mossy_stone_brick_stairs", "Mossy Stone Brick Stairs"},
        {"mossy_stone_brick_wall", "Mossy Stone Brick Wall"},
        {"mossy_stone_bricks", "Mossy Stone Bricks"},
        {"mushroom_stem", "Mushroom Stem"},
        {"mycelium", "Mycelium"},
        {"nether_brick_fence", "Nether Brick Fence"},
        {"nether_brick_slab", "Nether Brick Slab"},
        {"nether_brick_stairs", "Nether Brick Stairs"},
        {"nether_brick_wall", "Nether Brick Wall"},
        {"nether_bricks", "Nether Bricks"},
        {"nether_quartz_ore", "Nether Quartz Ore"},
        {"nether_wart_block", "Nether Wart Block"},
        {"nether_wart", "Nether Wart"},
        {"netherrack", "Netherrack"},
        {"note_block", "Note Block"},
        {"oak_button", "Oak Button"},
        {"oak_door", "Oak Door"},
        {"oak_fence_gate", "Oak Fence Gate"},
        {"oak_fence", "Oak Fence"},
        {"oak_leaves", "Oak Leaves"},
        {"oak_log", "Oak Log"},
        {"oak_planks", "Oak Planks"},
        {"oak_pressure_plate", "Oak Pressure Plate"},
        {"oak_sapling", "Oak Sapling"},
        {"oak_sign", "Oak Sign"},
        {"oak_slab", "Oak Slab"},
        {"oak_stairs", "Oak Stairs"},
        {"oak_trapdoor", "Oak Trapdoor"},
        {"oak_wood", "Oak Wood"},
        {"observer", "Observer"},
        {"obsidian", "Obsidian"},
        {"orange_banner", "Orange Banner"},
        {"orange_bed", "Orange Bed"},
        {"orange_carpet", "Orange Carpet"},
        {"orange_concrete_powder", "Orange Concrete Powder"},
        {"orange_concrete", "Orange Concrete"},
        {"orange_glazed_terracotta", "Orange Glazed Terracotta"},
        {"orange_shulker_box", "Orange Shulker Box"},
        {"orange_stained_glass", "Orange Stained Glass"},
        {"orange_stained_glass_pane", "Orange Stained Glass Pane"},
        {"orange_terracotta", "Orange Terracotta"},
        {"orange_tulip", "Orange Tulip"},
        {"orange_wool", "Orange Wool"},
        {"oxeye_daisy", "Oxeye Daisy"},
        {"packed_ice", "Packed Ice"},
        {"peony", "Peony"},
        {"petrified_oak_slab", "Petrified Oak Slab"},
        {"pink_banner", "Pink Banner"},
        {"pink_bed", "Pink Bed"},
        {"pink_carpet", "Pink Carpet"},
        {"pink_concrete_powder", "Pink Concrete Powder"},
        {"pink_concrete", "Pink Concrete"},
        {"pink_glazed_terracotta", "Pink Glazed Terracotta"},
        {"pink_shulker_box", "Pink Shulker Box"},
        {"pink_stained_glass", "Pink Stained Glass"},
        {"pink_stained_glass_pane", "Pink Stained Glass Pane"},
        {"pink_terracotta", "Pink Terracotta"},
        {"pink_tulip", "Pink Tulip"},
        {"pink_wool", "Pink Wool"},
        {"piston", "Piston"},
        {"player_head", "Player Head"},
        {"podzol", "Podzol"},
        {"polished_andesite", "Polished Andesite"},
        {"polished_andesite_slab", "Polished Andesite Slab"},
        {"polished_andesite_stairs", "Polished Andesite Stairs"},
        {"polished_diorite", "Polished Diorite"},
        {"polished_diorite_slab", "Polished Diorite Slab"},
        {"polished_diorite_stairs", "Polished Diorite Stairs"},
        {"polished_granite", "Polished Granite"},
        {"polished_granite_slab", "Polished Granite Slab"},
        {"polished_granite_stairs", "Polished Granite Stairs"},
        {"poppy", "Poppy"},
        {"powered_rail", "Powered Rail"},
        {"prismarine", "Prismarine"},
        {"prismarine_brick_slab", "Prismarine Brick Slab"},
        {"prismarine_brick_stairs", "Prismarine Brick Stairs"},
        {"prismarine_bricks", "Prismarine Bricks"},
        {"prismarine_slab", "Prismarine Slab"},
        {"prismarine_stairs", "Prismarine Stairs"},
        {"prismarine_wall", "Prismarine Wall"},
        {"pumpkin", "Pumpkin"},
        {"purple_banner", "Purple Banner"},
        {"purple_bed", "Purple Bed"},
        {"purple_carpet", "Purple Carpet"},
        {"purple_concrete_powder", "Purple Concrete Powder"},
        {"purple_concrete", "Purple Concrete"},
        {"purple_glazed_terracotta", "Purple Glazed Terracotta"},
        {"purple_shulker_box", "Purple Shulker Box"},
        {"purple_stained_glass", "Purple Stained Glass"},
        {"purple_stained_glass_pane", "Purple Stained Glass Pane"},
        {"purple_terracotta", "Purple Terracotta"},
        {"purple_wool", "Purple Wool"},
        {"purpur_block", "Purpur Block"},
        {"purpur_pillar", "Purpur Pillar"},
        {"purpur_slab", "Purpur Slab"},
        {"purpur_stairs", "Purpur Stairs"},
        {"quartz_block", "Block of Quartz"},
        {"quartz_pillar", "Quartz Pillar"},
        {"quartz_slab", "Quartz Slab"},
        {"quartz_stairs", "Quartz Stairs"},
        {"rail", "Rail"},
        {"red_banner", "Red Banner"},
        {"red_bed", "Red Bed"},
        {"red_carpet", "Red Carpet"},
        {"red_concrete_powder", "Red Concrete Powder"},
        {"red_concrete", "Red Concrete"},
        {"red_glazed_terracotta", "Red Glazed Terracotta"},
        {"red_mushroom_block", "Red Mushroom Block"},
        {"red_mushroom", "Red Mushroom"},
        {"red_nether_brick_slab", "Red Nether Brick Slab"},
        {"red_nether_brick_stairs", "Red Nether Brick Stairs"},
        {"red_nether_brick_wall", "Red Nether Brick Wall"},
        {"red_nether_bricks", "Red Nether Bricks"},
        {"red_sand", "Red Sand"},
        {"red_sandstone", "Red Sandstone"},
        {"red_sandstone_slab", "Red Sandstone Slab"},
        {"red_sandstone_stairs", "Red Sandstone Stairs"},
        {"red_sandstone_wall", "Red Sandstone Wall"},
        {"red_shulker_box", "Red Shulker Box"},
        {"red_stained_glass", "Red Stained Glass"},
        {"red_stained_glass_pane", "Red Stained Glass Pane"},
        {"red_terracotta", "Red Terracotta"},
        {"red_tulip", "Red Tulip"},
        {"red_wool", "Red Wool"},
        {"redstone_block", "Block of Redstone"},
        {"redstone_lamp", "Redstone Lamp"},
        {"redstone_ore", "Redstone Ore"},
        {"redstone_torch", "Redstone Torch"},
        {"repeater", "Redstone Repeater"},
        {"repeating_command_block", "Repeating Command Block"},
        {"rose_bush", "Rose Bush"},
        {"sand", "Sand"},
        {"sandstone", "Sandstone"},
        {"sandstone_slab", "Sandstone Slab"},
        {"sandstone_stairs", "Sandstone Stairs"},
        {"sandstone_wall", "Sandstone Wall"},
        {"scaffolding", "Scaffolding"},
        {"sea_lantern", "Sea Lantern"},
        {"sea_pickle", "Sea Pickle"},
        {"seagrass", "Seagrass"},
        {"shulker_box", "Shulker Box"},
        {"skeleton_skull", "Skeleton Skull"},
        {"slime_block", "Slime Block"},
        {"smithing_table", "Smithing Table"},
        {"smoker", "Smoker"},
        {"smooth_quartz", "Smooth Quartz"},
        {"smooth_quartz_slab", "Smooth Quartz Slab"},
        {"smooth_quartz_stairs", "Smooth Quartz Stairs"},
        {"smooth_red_sandstone", "Smooth Red Sandstone"},
        {"smooth_red_sandstone_slab", "Smooth Red Sandstone Slab"},
        {"smooth_red_sandstone_stairs", "Smooth Red Sandstone Stairs"},
        {"smooth_sandstone", "Smooth Sandstone"},
        {"smooth_sandstone_slab", "Smooth Sandstone Slab"},
        {"smooth_sandstone_stairs", "Smooth Sandstone Stairs"},
        {"smooth_stone", "Smooth Stone"},
        {"smooth_stone_slab", "Smooth Stone Slab"},
        {"snow_block", "Snow Block"},
        {"snow", "Snow"},
        {"soul_sand", "Soul Sand"},
        {"spawner", "Spawner"},
        {"sponge", "Sponge"},
        {"spruce_button", "Spruce Button"},
        {"spruce_door", "Spruce Door"},
        {"spruce_fence_gate", "Spruce Fence Gate"},
        {"spruce_fence", "Spruce Fence"},
        {"spruce_leaves", "Spruce Leaves"},
        {"spruce_log", "Spruce Log"},
        {"spruce_planks", "Spruce Planks"},
        {"spruce_pressure_plate", "Spruce Pressure Plate"},
        {"spruce_sapling", "Spruce Sapling"},
        {"spruce_sign", "Spruce Sign"},
        {"spruce_slab", "Spruce Slab"},
        {"spruce_stairs", "Spruce Stairs"},
        {"spruce_trapdoor", "Spruce Trapdoor"},
        {"spruce_wood", "Spruce Wood"},
        {"sticky_piston", "Sticky Piston"},
        {"stone", "Stone"},
        {"stone_brick_slab", "Stone Brick Slab"},
        {"stone_brick_stairs", "Stone Brick Stairs"},
        {"stone_brick_wall", "Stone Brick Wall"},
        {"stone_bricks", "Stone Bricks"},
        {"stone_button", "Stone Button"},
        {"stone_pressure_plate", "Stone Pressure Plate"},
        {"stone_slab", "Stone Slab"},
        {"stone_stairs", "Stone Stairs"},
        {"stonecutter", "Stonecutter"},
        {"stripped_acacia_log", "Stripped Acacia Log"},
        {"stripped_acacia_wood", "Stripped Acacia Wood"},
        {"stripped_birch_log", "Stripped Birch Log"},
        {"stripped_birch_wood", "Stripped Birch Wood"},
        {"stripped_dark_oak_log", "Stripped Dark Oak Log"},
        {"stripped_dark_oak_wood", "Stripped Dark Oak Wood"},
        {"stripped_jungle_log", "Stripped Jungle Log"},
        {"stripped_jungle_wood", "Stripped Jungle Wood"},
        {"stripped_oak_log", "Stripped Oak Log"},
        {"stripped_oak_wood", "Stripped Oak Wood"},
        {"stripped_spruce_log", "Stripped Spruce Log"},
        {"stripped_spruce_wood", "Stripped Spruce Wood"},
        {"structure_block", "Structure Block"},
        {"structure_void", "Structure Void"},
        {"sugar_cane", "Sugar Cane"},
        {"sunflower", "Sunflower"},
        {"tnt", "TNT"},
        {"tall_grass", "Tall Grass"},
        {"terracotta", "Terracotta"},
        {"torch", "Torch"},
        {"trapped_chest", "Trapped Chest"},
        {"tripwire_hook", "Tripwire Hook"},
        {"tube_coral", "Tube Coral"},
        {"tube_coral_block", "Tube Coral Block"},
        {"turtle_egg", "Turtle Egg"},
        {"vine", "Vines"},
        {"wet_sponge", "Wet Sponge"},
        {"white_banner", "White Banner"},
        {"white_bed", "White Bed"},
        {"white_carpet", "White Carpet"},
        {"white_concrete_powder", "White Concrete Powder"},
        {"white_concrete", "White Concrete"},
        {"white_glazed_terracotta", "White Glazed Terracotta"},
        {"white_shulker_box", "White Shulker Box"},
        {"white_stained_glass", "White Stained Glass"},
        {"white_stained_glass_pane", "White Stained Glass Pane"},
        {"white_terracotta", "White Terracotta"},
        {"white_tulip", "White Tulip"},
        {"white_wool", "White Wool"},
        {"wither_rose", "Wither Rose"},
        {"wither_skeleton_skull", "Wither Skeleton Skull"},
        {"yellow_banner", "Yellow Banner"},
        {"yellow_bed", "Yellow Bed"},
        {"yellow_carpet", "Yellow Carpet"},
        {"yellow_concrete_powder", "Yellow Concrete Powder"},
        {"yellow_concrete", "Yellow Concrete"},
        {"yellow_glazed_terracotta", "Yellow Glazed Terracotta"},
        {"yellow_shulker_box", "Yellow Shulker Box"},
        {"yellow_stained_glass", "Yellow Stained Glass"},
        {"yellow_stained_glass_pane", "Yellow Stained Glass Pane"},
        {"yellow_terracotta", "Yellow Terracotta"},
        {"yellow_wool", "Yellow Wool"},
        {"zombie_head", "Zombie Head"},
        {"acacia_boat", "Acacia Boat"},
        {"apple", "Apple"},
        {"armor_stand", "Armor Stand"},
        {"arrow", "Arrow"},
        {"baked_potato", "Baked Potato"},
        {"bat_spawn_egg", "Bat Spawn Egg"},
        {"beef", "Raw Beef"},
        {"beetroot_seeds", "Beetroot Seeds"},
        {"beetroot_soup", "Beetroot Soup"},
        {"beetroot", "Beetroot"},
        {"birch_boat", "Birch Boat"},
        {"black_dye", "Black Dye"},
        {"blaze_powder", "Blaze Powder"},
        {"blaze_rod", "Blaze Rod"},
        {"blaze_spawn_egg", "Blaze Spawn Egg"},
        {"blue_dye", "Blue Dye"},
        {"bone_meal", "Bone Meal"},
        {"bone", "Bone"},
        {"book", "Book"},
        {"writable_book", "Book and Quill"},
        {"experience_bottle", "Bottle o' Enchanting"},
        {"bowl", "Bowl"},
        {"bow", "Bow"},
        {"bread", "Bread"},
        {"brick", "Brick"},
        {"brown_dye", "Brown Dye"},
        {"bucket", "Bucket"},
        {"green_dye", "Green Dye"},
        {"carrot_on_a_stick", "Carrot on a Stick"},
        {"carrot", "Carrot"},
        {"cat_spawn_egg", "Cat Spawn Egg"},
        {"cave_spider_spawn_egg", "Cave Spider Spawn Egg"},
        {"chainmail_boots", "Chainmail Boots"},
        {"chainmail_chestplate", "Chainmail Chestplate"},
        {"chainmail_helmet", "Chainmail Helmet"},
        {"chainmail_leggings", "Chainmail Leggings"},
        {"charcoal", "Charcoal"},
        {"chest_minecart", "Minecart with Chest"},
        {"chicken", "Raw Chicken"},
        {"chicken_spawn_egg", "Chicken Spawn Egg"},
        {"chorus_fruit", "Chorus Fruit"},
        {"clay_ball", "Clay"},
        {"clock", "Clock"},
        {"coal", "Coal"},
        {"cocoa_beans", "Cocoa Beans"},
        {"cod", "Raw Cod"},
        {"cod_bucket", "Bucket of Cod"},
        {"cod_spawn_egg", "Cod Spawn Egg"},
        {"command_block_minecart", "Minecart with Command Block"},
        {"compass", "Compass"},
        {"cooked_chicken", "Cooked Chicken"},
        {"cooked_cod", "Cooked Cod"},
        {"cooked_mutton", "Cooked Mutton"},
        {"cooked_porkchop", "Cooked Porkchop"},
        {"cooked_rabbit", "Cooked Rabbit"},
        {"cooked_salmon", "Cooked Salmon"},
        {"cookie", "Cookie"},
        {"cow_spawn_egg", "Cow Spawn Egg"},
        {"creeper_banner_pattern", "Banner Pattern (Creeper Charge)"},
        {"creeper_spawn_egg", "Creeper Spawn Egg"},
        {"crossbow", "Crossbow"},
        {"cyan_dye", "Cyan Dye"},
        {"dark_oak_boat", "Dark Oak Boat"},
        {"debug_stick", "Debug Stick"},
        {"diamond_axe", "Diamond Axe"},
        {"diamond_boots", "Diamond Boots"},
        {"diamond_chestplate", "Diamond Chestplate"},
        {"diamond_helmet", "Diamond Helmet"},
        {"diamond_hoe", "Diamond Hoe"},
        {"diamond_horse_armor", "Diamond Horse Armor"},
        {"diamond_leggings", "Diamond Leggings"},
        {"diamond_pickaxe", "Diamond Pickaxe"},
        {"diamond_shovel", "Diamond Shovel"},
        {"diamond_sword", "Diamond Sword"},
        {"diamond", "Diamond"},
        {"dolphin_spawn_egg", "Dolphin Spawn Egg"},
        {"donkey_spawn_egg", "Donkey Spawn Egg"},
        {"dragon_breath", "Dragon's Breath"},
        {"dried_kelp", "Dried Kelp"},
        {"drowned_spawn_egg", "Drowned Spawn Egg"},
        {"egg", "Egg"},
        {"elder_guardian_spawn_egg", "Elder Guardian Spawn Egg"},
        {"elytra", "Elytra"},
        {"emerald", "Emerald"},
        {"map", "Empty Map"},
        {"enchanted_book", "Enchanted Book"},
        {"enchanted_golden_apple", "Enchanted Golden Apple"},
        {"end_crystal", "End Crystal"},
        {"ender_eye", "Eye of Ender"},
        {"ender_pearl", "Ender Pearl"},
        {"enderman_spawn_egg", "Enderman Spawn Egg"},
        {"endermite_spawn_egg", "Endermite Spawn Egg"},
        {"evoker_spawn_egg", "Evoker Spawn Egg"},
        {"feather", "Feather"},
        {"fermented_spider_eye", "Fermented Spider Eye"},
        {"fire_charge", "Fire Charge"},
        {"firework_rocket", "Firework Rocket"},
        {"firework_star", "Firework Star"},
        {"fishing_rod", "Fishing Rod"},
        {"flint", "Flint"},
        {"flint_and_steel", "Flint and Steel"},
        {"flower_banner_pattern", "Banner Pattern (Flower Charge)"},
        {"fox_spawn_egg", "Fox Spawn Egg"},
        {"furnace_minecart", "Minecart with Furnace"},
        {"ghast_spawn_egg", "Ghast Spawn Egg"},
        {"ghast_tear", "Ghast Tear"},
        {"glass_bottle", "Glass Bottle"},
        {"glistering_melon_slice", "Glistering Melon Slice"},
        {"globe_banner_pattern", "Banner Pattern (Globe)"},
        {"glowstone_dust", "Glowstone Dust"},
        {"gold_ingot", "Gold Ingot"},
        {"gold_nugget", "Gold Nugget"},
        {"golden_apple", "Golden Apple"},
        {"golden_axe", "Golden Axe"},
        {"golden_boots", "Golden Boots"},
        {"golden_carrot", "Golden Carrot"},
        {"golden_chestplate", "Golden Chestplate"},
        {"golden_helmet", "Golden Helmet"},
        {"golden_hoe", "Golden Hoe"},
        {"golden_horse_armor", "Golden Horse Armor"},
        {"golden_leggings", "Golden Leggings"},
        {"golden_pickaxe", "Golden Pickaxe"},
        {"golden_shovel", "Golden Shovel"},
        {"golden_sword", "Golden Sword"},
        {"gray_dye", "Gray Dye"},
        {"guardian_spawn_egg", "Guardian Spawn Egg"},
        {"gunpowder", "Gunpowder"},
        {"heart_of_the_sea", "Heart of the Sea"},
        {"hopper_minecart", "Minecart with Hopper"},
        {"horse_spawn_egg", "Horse Spawn Egg"},
        {"husk_spawn_egg", "Husk Spawn Egg"},
        {"ink_sac", "Ink Sac"},
        {"iron_axe", "Iron Axe"},
        {"iron_boots", "Iron Boots"},
        {"iron_chestplate", "Iron Chestplate"},
        {"iron_helmet", "Iron Helmet"},
        {"iron_hoe", "Iron Hoe"},
        {"iron_horse_armor", "Iron Horse Armor"},
        {"iron_ingot", "Iron Ingot"},
        {"iron_leggings", "Iron Leggings"},
        {"iron_nugget", "Iron Nugget"},
        {"iron_pickaxe", "Iron Pickaxe"},
        {"iron_shovel", "Iron Shovel"},
        {"iron_sword", "Iron Sword"},
        {"item_frame", "Item Frame"},
        {"jungle_boat", "Jungle Boat"},
        {"knowledge_book", "Knowledge Book"},
        {"lapis_lazuli", "Lapis Lazuli"},
        {"lava_bucket", "Lava Bucket"},
        {"lead", "Lead"},
        {"leather", "Leather"},
        {"leather_boots", "Leather Boots"},
        {"leather_helmet", "Leather Cap"},
        {"leather_horse_armor", "Leather Horse Armor"},
        {"leather_leggings", "Leather Pants"},
        {"leather_chestplate", "Leather Tunic"},
        {"light_blue_dye", "Light Blue Dye"},
        {"light_gray_dye", "Light Gray Dye"},
        {"lime_dye", "Lime Dye"},
        {"lingering_potion", "Lingering Potions"},
        {"llama_spawn_egg", "Llama Spawn Egg"},
        {"magenta_dye", "Magenta Dye"},
        {"magma_cream", "Magma Cream"},
        {"magma_cube_spawn_egg", "Magma Cube Spawn Egg"},
        {"filled_map", "Map or Explorer Map"},
        {"melon_seeds", "Melon Seeds"},
        {"melon_slice", "Melon Slice"},
        {"milk_bucket", "Milk Bucket"},
        {"minecart", "Minecart"},
        {"mojang_banner_pattern", "Banner Pattern (Thing)"},
        {"mooshroom_spawn_egg", "Mooshroom Spawn Egg"},
        {"mule_spawn_egg", "Mule Spawn Egg"},
        {"mushroom_stew", "Mushroom Stew"},
        {"music_disc_11", "Music Disc (11)"},
        {"music_disc_13", "Music Disc (13)"},
        {"music_disc_blocks", "Music Disc (Blocks)"},
        {"music_disc_cat", "Music Disc (Cat)"},
        {"music_disc_chirp", "Music Disc (Chirp)"},
        {"music_disc_far", "Music Disc (Far)"},
        {"music_disc_mall", "Music Disc (Mall)"},
        {"music_disc_mellohi", "Music Disc (Mellohi)"},
        {"music_disc_stal", "Music Disc (Stal)"},
        {"music_disc_strad", "Music Disc (Strad)"},
        {"music_disc_wait", "Music Disc (Wait)"},
        {"music_disc_ward", "Music Disc (Ward)"},
        {"mutton", "Raw Mutton"},
        {"name_tag", "Name Tag"},
        {"nautilus_shell", "Nautilus Shell"},
        {"nether_brick", "Nether Brick"},
        {"quartz", "Nether Quartz"},
        {"nether_star", "Nether Star"},
        {"oak_boat", "Oak Boat"},
        {"ocelot_spawn_egg", "Ocelot Spawn Egg"},
        {"orange_dye", "Orange Dye"},
        {"painting", "Painting"},
        {"panda_spawn_egg", "Panda Spawn Egg"},
        {"paper", "Paper"},
        {"parrot_spawn_egg", "Parrot Spawn Egg"},
        {"phantom_membrane", "Phantom Membrane"},
        {"phantom_spawn_egg", "Phantom Spawn Egg"},
        {"pig_spawn_egg", "Pig Spawn Egg"},
        {"pillager_spawn_egg", "Pillager Spawn Egg"},
        {"pink_dye", "Pink Dye"},
        {"poisonous_potato", "Poisonous Potato"},
        {"polar_bear_spawn_egg", "Polar Bear Spawn Egg"},
        {"popped_chorus_fruit", "Popped Chorus Fruit"},
        {"porkchop", "Raw Porkchop"},
        {"potato", "Potato"},
        {"potion", "Potions"},
        {"prismarine_crystals", "Prismarine Crystals"},
        {"prismarine_shard", "Prismarine Shard"},
        {"pufferfish", "Pufferfish"},
        {"pufferfish_bucket", "Bucket of Pufferfish"},
        {"pufferfish_spawn_egg", "Pufferfish Spawn Egg"},
        {"pumpkin_pie", "Pumpkin Pie"},
        {"pumpkin_seeds", "Pumpkin Seeds"},
        {"purple_dye", "Purple Dye"},
        {"rabbit", "Raw Rabbit"},
        {"rabbit_foot", "Rabbit's Foot"},
        {"rabbit_hide", "Rabbit Hide"},
        {"rabbit_spawn_egg", "Rabbit Spawn Egg"},
        {"rabbit_stew", "Rabbit Stew"},
        {"ravager_spawn_egg", "Ravager Spawn Egg"},
        {"redstone", "Redstone Dust"},
        {"red_dye", "Red Dye"},
        {"rotten_flesh", "Rotten Flesh"},
        {"saddle", "Saddle"},
        {"salmon", "Raw Salmon"},
        {"salmon_bucket", "Bucket of Salmon"},
        {"salmon_spawn_egg", "Salmon Spawn Egg"},
        {"scute", "Scute"},
        {"shears", "Shears"},
        {"sheep_spawn_egg", "Sheep Spawn Egg"},
        {"shield", "Shield"},
        {"shulker_shell", "Shulker Shell"},
        {"shulker_spawn_egg", "Shulker Spawn Egg"},
        {"silverfish_spawn_egg", "Silverfish Spawn Egg"},
        {"skeleton_horse_spawn_egg", "Skeleton Horse Spawn Egg"},
        {"skeleton_spawn_egg", "Skeleton Spawn Egg"},
        {"skull_banner_pattern", "Banner Pattern (Skull Charge)"},
        {"slime_spawn_egg", "Slime Spawn Egg"},
        {"slime_ball", "Slimeball"},
        {"snowball", "Snowball"},
        {"spectral_arrow", "Spectral Arrow"},
        {"spider_eye", "Spider Eye"},
        {"spider_spawn_egg", "Spider Spawn Egg"},
        {"splash_potion", "Splash Potions"},
        {"spruce_boat", "Spruce Boat"},
        {"squid_spawn_egg", "Squid Spawn Egg"},
        {"cooked_beef", "Steak"},
        {"stick", "Stick"},
        {"stone_axe", "Stone Axe"},
        {"stone_hoe", "Stone Hoe"},
        {"stone_pickaxe", "Stone Pickaxe"},
        {"stone_shovel", "Stone Shovel"},
        {"stone_sword", "Stone Sword"},
        {"stray_spawn_egg", "Stray Spawn Egg"},
        {"string", "String"},
        {"sugar", "Sugar"},
        {"suspicious_stew", "Suspicious Stew"},
        {"sweet_berries", "Sweet Berries"},
        {"tipped_arrow", "Tipped Arrows"},
        {"tnt_minecart", "Minecart with TNT"},
        {"totem_of_undying", "Totem of Undying"},
        {"trader_llama_spawn_egg", "Trader Llama Spawn Egg"},
        {"trident", "Trident"},
        {"tropical_fish", "Tropical Fish"},
        {"tropical_fish_bucket", "Bucket of Tropical Fish"},
        {"tropical_fish_spawn_egg", "Tropical Fish Spawn Egg"},
        {"turtle_helmet", "Turtle Shell"},
        {"turtle_spawn_egg", "Turtle Spawn Egg"},
        {"vex_spawn_egg", "Vex Spawn Egg"},
        {"villager_spawn_egg", "Villager Spawn Egg"},
        {"vindicator_spawn_egg", "Vindicator Spawn Egg"},
        {"wandering_trader_spawn_egg", "Wandering Trader Spawn Egg"},
        {"water_bucket", "Water Bucket"},
        {"wheat_seeds", "Wheat Seeds"},
        {"wheat", "Wheat"},
        {"white_dye", "White Dye"},
        {"witch_spawn_egg", "Witch Spawn Egg"},
        {"wither_skeleton_spawn_egg", "Wither Skeleton Spawn Egg"},
        {"wolf_spawn_egg", "Wolf Spawn Egg"},
        {"wooden_axe", "Wooden Axe"},
        {"wooden_hoe", "Wooden Hoe"},
        {"wooden_pickaxe", "Wooden Pickaxe"},
        {"wooden_shovel", "Wooden Shovel"},
        {"wooden_sword", "Wooden Sword"},
        {"written_book", "Written Book"},
        {"yellow_dye", "Yellow Dye"},
        {"zombie_horse_spawn_egg", "Zombie Horse Spawn Egg"},
        {"zombie_pigman_spawn_egg", "Zombie Pigman Spawn Egg"},
        {"zombie_spawn_egg", "Zombie Spawn Egg"},
        {"zombie_villager_spawn_egg", "Zombie Villager Spawn Egg"},
    };
    return itemlist;
}
