#ifndef NODEVISITOR_H
#define NODEVISITOR_H

namespace Command {
    class ParseNode;
    class ErrorNode;
    class RootNode;
    class ArgumentNode;
    class BoolNode;
    class DoubleNode;
    class FloatNode;
    class IntegerNode;
    class LongNode;
    class StringNode;
    class LiteralNode;
    class AngleNode;
    class BlockPosNode;
    class BlockPredicateNode;
    class BlockStateNode;
    class ColorNode;
    class ColumnPosNode;
    class ComponentNode;
    class DimensionNode;
    class EntityAnchorNode;
    class InvertibleNode;
    class EntityNode;
    class EntitySummonNode;
    class FloatRangeNode;
    class FunctionNode;
    class GameProfileNode;
    class GamemodeNode;
    class HeightmapNode;
    class InlinableResourceNode;
    class IntRangeNode;
    class ItemEnchantmentNode;
    class ItemPredicateNode;
    class ItemPredicateMatchNode;
    class ItemSlotNode;
    class ItemSlotsNode;
    class ItemStackNode;
    class KeyNode;
    class ListNode;
    class LootModifierNode;
    class LootPredicateNode;
    class LootTableNode;
    class MapNode;
    class MessageNode;
    class MobEffectNode;
    class NbtByteArrayNode;
    class NbtByteNode;
    class NbtCompoundNode;
    class NbtDoubleNode;
    class NbtFloatNode;
    class NbtIntArrayNode;
    class NbtIntNode;
    class NbtListNode;
    class NbtLongArrayNode;
    class NbtLongNode;
    class NbtNode;
    class NbtPathNode;
    class NbtPathStepNode;
    class NbtShortNode;
    class NbtStringNode;
    class ObjectiveCriteriaNode;
    class ObjectiveNode;
    class OperationNode;
    class ParticleColorNode;
    class ParticleNode;
    class ResourceKeyNode;
    class ResourceLocationNode;
    class ResourceNode;
    class ResourceOrTagKeyNode;
    class ResourceOrTagNode;
    class RotationNode;
    class ScoreHolderNode;
    class ScoreboardSlotNode;
    class StyleNode;
    class SwizzleNode;
    class TargetSelectorNode;
    class TeamNode;
    class TemplateMirrorNode;
    class TemplateRotationNode;
    class TimeNode;
    class TwoAxesNode;
    class UuidNode;
    class Vec2Node;
    class Vec3Node;
    class XyzNode;
    class InternalGreedyStringNode;
    class InternalRegexPatternNode;

    enum VisitOrder: int { Preorder, Postorder, LetTheVisitorDecide };

    class NodeVisitor {
public:
        NodeVisitor(VisitOrder order) : m_order(order) {
        };

        void startVisiting(ParseNode *node);

        virtual void visit(ParseNode *node)                = 0;
        virtual void visit(ErrorNode *node)                = 0;
        virtual void visit(RootNode *node)                 = 0;
        virtual void visit(ArgumentNode *node)             = 0;
        virtual void visit(BoolNode *node)                 = 0;
        virtual void visit(DoubleNode *node)               = 0;
        virtual void visit(FloatNode *node)                = 0;
        virtual void visit(IntegerNode *node)              = 0;
        virtual void visit(LongNode *node)                 = 0;
        virtual void visit(StringNode *node)               = 0;
        virtual void visit(LiteralNode *node)              = 0;
        virtual void visit(AngleNode *node)                = 0;
        virtual void visit(BlockPosNode *node)             = 0;
        virtual void visit(BlockPredicateNode *node)       = 0;
        virtual void visit(BlockStateNode *node)           = 0;
        virtual void visit(ColorNode *node)                = 0;
        virtual void visit(ColumnPosNode *node)            = 0;
        virtual void visit(ComponentNode *node)            = 0;
        virtual void visit(DimensionNode *node)            = 0;
        virtual void visit(EntityAnchorNode *node)         = 0;
        virtual void visit(InvertibleNode *node)           = 0;
        virtual void visit(EntityNode *node)               = 0;
        virtual void visit(EntitySummonNode *node)         = 0;
        virtual void visit(FloatRangeNode *node)           = 0;
        virtual void visit(FunctionNode *node)             = 0;
        virtual void visit(GameProfileNode *node)          = 0;
        virtual void visit(GamemodeNode *node)             = 0;
        virtual void visit(HeightmapNode *node)            = 0;
        virtual void visit(InlinableResourceNode *node)    = 0;
        virtual void visit(IntRangeNode *node)             = 0;
        virtual void visit(ItemEnchantmentNode *node)      = 0;
        virtual void visit(ItemPredicateNode *node)        = 0;
        virtual void visit(ItemPredicateMatchNode *node)   = 0;
        virtual void visit(ItemSlotNode *node)             = 0;
        virtual void visit(ItemSlotsNode *node)            = 0;
        virtual void visit(ItemStackNode *node)            = 0;
        virtual void visit(KeyNode *node)                  = 0;
        virtual void visit(ListNode *node)                 = 0;
        virtual void visit(LootModifierNode *node)         = 0;
        virtual void visit(LootPredicateNode *node)        = 0;
        virtual void visit(LootTableNode *node)            = 0;
        virtual void visit(MapNode *node)                  = 0;
        virtual void visit(MessageNode *node)              = 0;
        virtual void visit(MobEffectNode *node)            = 0;
        virtual void visit(NbtByteArrayNode *node)         = 0;
        virtual void visit(NbtByteNode *node)              = 0;
        virtual void visit(NbtCompoundNode *node)          = 0;
        virtual void visit(NbtDoubleNode *node)            = 0;
        virtual void visit(NbtFloatNode *node)             = 0;
        virtual void visit(NbtIntArrayNode *node)          = 0;
        virtual void visit(NbtIntNode *node)               = 0;
        virtual void visit(NbtListNode *node)              = 0;
        virtual void visit(NbtLongArrayNode *node)         = 0;
        virtual void visit(NbtLongNode *node)              = 0;
        virtual void visit(NbtNode *node)                  = 0;
        virtual void visit(NbtPathNode *node)              = 0;
        virtual void visit(NbtPathStepNode *node)          = 0;
        virtual void visit(NbtShortNode *node)             = 0;
        virtual void visit(NbtStringNode *node)            = 0;
        virtual void visit(ObjectiveCriteriaNode *node)    = 0;
        virtual void visit(ObjectiveNode *node)            = 0;
        virtual void visit(OperationNode *node)            = 0;
        virtual void visit(ParticleColorNode *node)        = 0;
        virtual void visit(ParticleNode *node)             = 0;
        virtual void visit(ResourceKeyNode *node)          = 0;
        virtual void visit(ResourceLocationNode *node)     = 0;
        virtual void visit(ResourceNode *node)             = 0;
        virtual void visit(ResourceOrTagKeyNode *node)     = 0;
        virtual void visit(ResourceOrTagNode *node)        = 0;
        virtual void visit(RotationNode *node)             = 0;
        virtual void visit(ScoreHolderNode *node)          = 0;
        virtual void visit(ScoreboardSlotNode *node)       = 0;
        virtual void visit(StyleNode *node)                = 0;
        virtual void visit(SwizzleNode *node)              = 0;
        virtual void visit(TargetSelectorNode *node)       = 0;
        virtual void visit(TeamNode *node)                 = 0;
        virtual void visit(TemplateMirrorNode *node)       = 0;
        virtual void visit(TemplateRotationNode *node)     = 0;
        virtual void visit(TimeNode *node)                 = 0;
        virtual void visit(TwoAxesNode *node)              = 0;
        virtual void visit(UuidNode *node)                 = 0;
        virtual void visit(Vec2Node *node)                 = 0;
        virtual void visit(Vec3Node *node)                 = 0;
        virtual void visit(XyzNode *node)                  = 0;
        virtual void visit(InternalGreedyStringNode *node) = 0;
        virtual void visit(InternalRegexPatternNode *node) = 0;

protected:
        VisitOrder m_order = VisitOrder::Postorder;
    };
}

#endif /* NODEVISITOR_H */
