/* Generated by re2c 3.0 on Sat Mar 25 14:11:23 2023 */
#line 1 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
#line 5 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"

#line 92 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"


#include "re2c_generated_functions.h"

#define YYCTYPE    QChar

namespace re2c {
    QStringView decimal(QStringView input) {
        const QChar *YYCURSOR = input.cbegin();
        const QChar *YYMARKER = nullptr;

        
#line 19 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if (yych <= '-') {
		if (yych == '+') goto yy3;
		if (yych >= '-') goto yy3;
	} else {
		if (yych <= '.') goto yy4;
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy5;
	}
yy1:
	++YYCURSOR;
yy2:
#line 108 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(); }
#line 36 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy3:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == '.') goto yy7;
	if (yych <= '/') goto yy2;
	if (yych <= '9') goto yy5;
	goto yy2;
yy4:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy2;
	if (yych <= '9') goto yy9;
	goto yy2;
yy5:
	yych = *++YYCURSOR;
	if (yych == '.') goto yy9;
	if (yych <= '/') goto yy6;
	if (yych <= '9') goto yy5;
yy6:
#line 107 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(input.cbegin(), YYCURSOR); }
#line 56 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy7:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy8;
	if (yych <= '9') goto yy9;
yy8:
	YYCURSOR = YYMARKER;
	goto yy2;
yy9:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy6;
	if (yych <= '9') goto yy9;
	goto yy6;
}
#line 109 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"

    }

    QStringView itemSlot(QStringView input) {
        const QChar *YYCURSOR = input.cbegin();
        const QChar *YYMARKER = nullptr;

        
#line 79 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if (yych <= '9') {
		if (yych == '.') goto yy12;
		if (yych >= '0') goto yy12;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy12;
		} else {
			if (yych <= '`') goto yy11;
			if (yych <= 'z') goto yy12;
		}
	}
yy11:
	++YYCURSOR;
#line 120 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(); }
#line 98 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy12:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '.') goto yy12;
		if (yych >= '0') goto yy12;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy12;
		} else {
			if (yych <= '`') goto yy13;
			if (yych <= 'z') goto yy12;
		}
	}
yy13:
#line 119 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(input.cbegin(), YYCURSOR); }
#line 115 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
}
#line 121 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"

    }

    QStringView nbtPathKey(QStringView input) {
        const QChar *YYCURSOR = input.cbegin();
        const QChar *YYMARKER = nullptr;

        
#line 126 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych == '+') goto yy16;
		} else {
			if (yych <= '-') goto yy16;
			if (yych >= '0') goto yy16;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy15;
			if (yych <= 'Z') goto yy16;
		} else {
			if (yych == '`') goto yy15;
			if (yych <= 'z') goto yy16;
		}
	}
yy15:
	++YYCURSOR;
#line 132 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(); }
#line 150 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy16:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych == '+') goto yy16;
		} else {
			if (yych <= '-') goto yy16;
			if (yych >= '0') goto yy16;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy17;
			if (yych <= 'Z') goto yy16;
		} else {
			if (yych == '`') goto yy17;
			if (yych <= 'z') goto yy16;
		}
	}
yy17:
#line 131 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(input.cbegin(), YYCURSOR); }
#line 172 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
}
#line 133 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"

    }

    QStringView objective(QStringView input) {
        const QChar *YYCURSOR = input.cbegin();
        const QChar *YYMARKER = nullptr;

        
#line 183 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if (yych <= '/') {
		if (yych <= '*') {
			if (yych == '#') goto yy20;
		} else {
			if (yych == ',') goto yy19;
			if (yych <= '.') goto yy20;
		}
	} else {
		if (yych <= '^') {
			if (yych <= ':') goto yy20;
			if (yych <= '@') goto yy19;
			if (yych <= 'Z') goto yy20;
		} else {
			if (yych == '`') goto yy19;
			if (yych <= 'z') goto yy20;
		}
	}
yy19:
	++YYCURSOR;
#line 144 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(); }
#line 208 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy20:
	yych = *++YYCURSOR;
	if (yych <= '/') {
		if (yych <= '*') {
			if (yych == '#') goto yy20;
		} else {
			if (yych == ',') goto yy21;
			if (yych <= '.') goto yy20;
		}
	} else {
		if (yych <= '^') {
			if (yych <= ':') goto yy20;
			if (yych <= '@') goto yy21;
			if (yych <= 'Z') goto yy20;
		} else {
			if (yych == '`') goto yy21;
			if (yych <= 'z') goto yy20;
		}
	}
yy21:
#line 143 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(input.cbegin(), YYCURSOR); }
#line 231 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
}
#line 145 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"

    }

    QStringView objectiveCriteria(QStringView input) {
        const QChar *YYCURSOR = input.cbegin();
        const QChar *YYMARKER = nullptr;

        
#line 242 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if (yych <= '-') goto yy23;
	if (yych == '`') goto yy23;
	if (yych <= 'z') goto yy24;
yy23:
	++YYCURSOR;
#line 156 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(); }
#line 253 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy24:
	yych = *++YYCURSOR;
	if (yych <= '-') goto yy25;
	if (yych == '`') goto yy25;
	if (yych <= 'z') goto yy24;
yy25:
#line 155 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(input.cbegin(), YYCURSOR); }
#line 262 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
}
#line 157 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"

    }

    QStringView realPlayerName(QStringView input) {
        const QChar *YYCURSOR = input.cbegin();
        const QChar *YYMARKER = nullptr;

        
#line 273 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy27;
		if (yych <= '9') goto yy28;
		if (yych >= 'A') goto yy28;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy28;
		} else {
			if (yych <= '`') goto yy27;
			if (yych <= 'z') goto yy28;
		}
	}
yy27:
	++YYCURSOR;
#line 168 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(); }
#line 293 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy28:
	yych = *++YYCURSOR;
	if (yych <= 'Z') {
		if (yych <= '/') goto yy29;
		if (yych <= '9') goto yy28;
		if (yych >= 'A') goto yy28;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy28;
		} else {
			if (yych <= '`') goto yy29;
			if (yych <= 'z') goto yy28;
		}
	}
yy29:
#line 167 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(input.cbegin(), YYCURSOR); }
#line 311 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
}
#line 169 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"

    }

    QStringView resLocPart(QStringView input) {
        const QChar *YYCURSOR = input.cbegin();
        const QChar *YYMARKER = nullptr;

        
#line 322 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if (yych <= '\\') {
		if (yych <= ',') goto yy31;
		if (yych <= '9') goto yy32;
		if (yych >= '\\') goto yy32;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy32;
		} else {
			if (yych <= '`') goto yy31;
			if (yych <= 'z') goto yy32;
		}
	}
yy31:
	++YYCURSOR;
#line 180 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(); }
#line 342 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy32:
	yych = *++YYCURSOR;
	if (yych <= '\\') {
		if (yych <= ',') goto yy33;
		if (yych <= '9') goto yy32;
		if (yych >= '\\') goto yy32;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy32;
		} else {
			if (yych <= '`') goto yy33;
			if (yych <= 'z') goto yy32;
		}
	}
yy33:
#line 179 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(input.cbegin(), YYCURSOR); }
#line 360 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
}
#line 181 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"

    }

    QStringView uuid(QStringView input, QUuid &result) {
        const QChar *YYCURSOR = input.cbegin();
        const QChar *YYMARKER = nullptr;

    #define DECLARE_PART_POINTERS(part)    const QChar *_p ## part, \
            *p ## part ## _;
        DECLARE_PART_POINTERS(1);
        DECLARE_PART_POINTERS(2);
        DECLARE_PART_POINTERS(3);
        DECLARE_PART_POINTERS(4);
        DECLARE_PART_POINTERS(5);
    #undef DECLARE_PART_POINTERS

    #define GET_PART(part)    QStringView(_p ## part, p ## part ## _)

        
#line 382 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
const QChar *yyt1;
const QChar *yyt2;
const QChar *yyt3;
const QChar *yyt4;
const QChar *yyt5;
#line 199 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"


        
#line 392 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy35;
		if (yych <= '9') {
			yyt1 = YYCURSOR;
			goto yy37;
		}
	} else {
		if (yych <= 'F') {
			yyt1 = YYCURSOR;
			goto yy37;
		}
		if (yych <= '`') goto yy35;
		if (yych <= 'f') {
			yyt1 = YYCURSOR;
			goto yy37;
		}
	}
yy35:
	++YYCURSOR;
yy36:
#line 234 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{ return QStringView(); }
#line 418 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy37:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '9') {
		if (yych == '-') goto yy38;
		if (yych <= '/') goto yy36;
		goto yy40;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy36;
			goto yy40;
		} else {
			if (yych <= '`') goto yy36;
			if (yych <= 'f') goto yy40;
			goto yy36;
		}
	}
yy38:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy39;
		if (yych <= '9') {
			yyt2 = YYCURSOR;
			goto yy41;
		}
	} else {
		if (yych <= 'F') {
			yyt2 = YYCURSOR;
			goto yy41;
		}
		if (yych <= '`') goto yy39;
		if (yych <= 'f') {
			yyt2 = YYCURSOR;
			goto yy41;
		}
	}
yy39:
	YYCURSOR = YYMARKER;
	goto yy36;
yy40:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy38;
		if (yych <= '/') goto yy39;
		goto yy42;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy42;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy42;
			goto yy39;
		}
	}
yy41:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy43;
		if (yych <= '/') goto yy39;
		goto yy44;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy44;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy44;
			goto yy39;
		}
	}
yy42:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy38;
		if (yych <= '/') goto yy39;
		goto yy45;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy45;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy45;
			goto yy39;
		}
	}
yy43:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy39;
		if (yych <= '9') {
			yyt3 = YYCURSOR;
			goto yy46;
		}
		goto yy39;
	} else {
		if (yych <= 'F') {
			yyt3 = YYCURSOR;
			goto yy46;
		}
		if (yych <= '`') goto yy39;
		if (yych <= 'f') {
			yyt3 = YYCURSOR;
			goto yy46;
		}
		goto yy39;
	}
yy44:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy43;
		if (yych <= '/') goto yy39;
		goto yy47;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy47;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy47;
			goto yy39;
		}
	}
yy45:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy38;
		if (yych <= '/') goto yy39;
		goto yy48;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy48;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy48;
			goto yy39;
		}
	}
yy46:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy49;
		if (yych <= '/') goto yy39;
		goto yy50;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy50;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy50;
			goto yy39;
		}
	}
yy47:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy43;
		if (yych <= '/') goto yy39;
		goto yy51;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy51;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy51;
			goto yy39;
		}
	}
yy48:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy38;
		if (yych <= '/') goto yy39;
		goto yy52;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy52;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy52;
			goto yy39;
		}
	}
yy49:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy39;
		if (yych <= '9') {
			yyt4 = YYCURSOR;
			goto yy53;
		}
		goto yy39;
	} else {
		if (yych <= 'F') {
			yyt4 = YYCURSOR;
			goto yy53;
		}
		if (yych <= '`') goto yy39;
		if (yych <= 'f') {
			yyt4 = YYCURSOR;
			goto yy53;
		}
		goto yy39;
	}
yy50:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy49;
		if (yych <= '/') goto yy39;
		goto yy54;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy54;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy54;
			goto yy39;
		}
	}
yy51:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy43;
	goto yy39;
yy52:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy38;
		if (yych <= '/') goto yy39;
		goto yy55;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy55;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy55;
			goto yy39;
		}
	}
yy53:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy56;
		if (yych <= '/') goto yy39;
		goto yy57;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy57;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy57;
			goto yy39;
		}
	}
yy54:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy49;
		if (yych <= '/') goto yy39;
		goto yy58;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy58;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy58;
			goto yy39;
		}
	}
yy55:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy38;
		if (yych <= '/') goto yy39;
		goto yy59;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy59;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy59;
			goto yy39;
		}
	}
yy56:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy39;
		if (yych <= '9') {
			yyt5 = YYCURSOR;
			goto yy60;
		}
		goto yy39;
	} else {
		if (yych <= 'F') {
			yyt5 = YYCURSOR;
			goto yy60;
		}
		if (yych <= '`') goto yy39;
		if (yych <= 'f') {
			yyt5 = YYCURSOR;
			goto yy60;
		}
		goto yy39;
	}
yy57:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy56;
		if (yych <= '/') goto yy39;
		goto yy62;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy62;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy62;
			goto yy39;
		}
	}
yy58:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy49;
	goto yy39;
yy59:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy38;
	goto yy39;
yy60:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych <= '9') goto yy63;
	} else {
		if (yych <= 'F') goto yy63;
		if (yych <= '`') goto yy61;
		if (yych <= 'f') goto yy63;
	}
yy61:
	_p1 = yyt1;
	_p2 = yyt2;
	_p3 = yyt3;
	_p4 = yyt4;
	_p5 = yyt5;
	p1_ = yyt2 - 1;
	p2_ = yyt3 - 1;
	p3_ = yyt4 - 1;
	p4_ = yyt5 - 1;
	p5_ = YYCURSOR;
#line 207 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"
	{
                bool              ok;
                constexpr static uint8_t last2HexDigitMask = 0xff;

                const auto l             = strToUHex<uint32_t>(GET_PART(1), ok);
                const auto w1            = strToUHex<uint16_t>(GET_PART(2), ok);
                const auto w2            = strToUHex<uint16_t>(GET_PART(3), ok);
                const auto clock_seq_low = strToUHex<uint16_t>(GET_PART(4), ok);

                const uint8_t b1   = clock_seq_low >> 8;
                const uint8_t b2   = clock_seq_low & last2HexDigitMask;
                auto          node = strToUHex<uint64_t>(GET_PART(5), ok);
                const uint8_t b8   = node & last2HexDigitMask;
                node >>= 8;
                const uint8_t b7 = node & last2HexDigitMask;
                node >>= 8;
                const uint8_t b6 = node & last2HexDigitMask;
                node >>= 8;
                const uint8_t b5 = node & last2HexDigitMask;
                node >>= 8;
                const uint8_t b4 = node & last2HexDigitMask;
                node >>= 8;
                const uint8_t b3 = node;

                result = QUuid{l, w1, w2, b1, b2, b3, b4, b5, b6, b7, b8};
                return QStringView(input.cbegin(), YYCURSOR);
            }
#line 805 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_generated_functions.cpp"
yy62:
	yych = *++YYCURSOR;
	if (yych <= '9') {
		if (yych == '-') goto yy56;
		if (yych <= '/') goto yy39;
		goto yy64;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy39;
			goto yy64;
		} else {
			if (yych <= '`') goto yy39;
			if (yych <= 'f') goto yy64;
			goto yy39;
		}
	}
yy63:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych <= '9') goto yy65;
		goto yy61;
	} else {
		if (yych <= 'F') goto yy65;
		if (yych <= '`') goto yy61;
		if (yych <= 'f') goto yy65;
		goto yy61;
	}
yy64:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy56;
	goto yy39;
yy65:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy66;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy66:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy67;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy67:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy68;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy68:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy69;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy69:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy70;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy70:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy71;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy71:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy72;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy72:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy73;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy73:
	yych = *++YYCURSOR;
	if (yych <= '@') {
		if (yych <= '/') goto yy61;
		if (yych >= ':') goto yy61;
	} else {
		if (yych <= 'F') goto yy74;
		if (yych <= '`') goto yy61;
		if (yych >= 'g') goto yy61;
	}
yy74:
	++YYCURSOR;
	goto yy61;
}
#line 235 "D:\\C++\\Qt\\MCDatapacker\\src\\parsers\\command\\re2c_functions.re"


    #undef GET_PART
    }
}


#undef YYCTYPE
